### ISSUE TITLE
Cuda runtime Error

### ISSUE THREAD

**Issue by l1a0t1n9** [ly015/age#1]
hello, interested in your code, but when I run age_model.py， it shows error:

`THCudaCheck FAIL file=/home/deeplearning/Liaoting/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "modules/age_model.py", line 956, in <module>
    train_model(model, train_opts)
  File "modules/age_model.py", line 450, in train_model
    age_out, fc_out = model(img)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "modules/age_model.py", line 190, in forward
    feat = self.cnn(img)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 72, in forward

    input = module(input)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 72, in forward

    input = module(input)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torchvision/models/resnet.py", line 45, in forward
    out = self.conv2(out)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /home/deeplearning/Liaoting/pytorch/aten/src/THC/generic/THCStorage.cu:58`

please check what's wrong, or maybe just a slight memory leak. 
BTW. my gpu is GTX 1080. and set batch_size from 64 to 16 both train and test, always wrong!

**Comment by l1a0t1n9** [comment]
i have fixed it.
